[project]
name = "phd-thesis"
version = "0.1.0"
description = "My PhD thesis at the University of Zurich"
authors = ["Martin Stancsics <martin.stancsics@gmail.com>"]
channels = ["conda-forge", "bioconda"]
platforms = ["linux-64", "win-64", "osx-arm64"]

[tasks]
prepare-to-publish = "snakemake --cores 1 prepare_to_publish"
dissertation = "snakemake --cores 1 dissertation"
papers = "snakemake --cores 1 papers"
presentations = "snakemake --cores 1 presentations"
update-latex-deps = "snakemake --cores 1 update_latex_deps"

[dependencies]
altair = "5.3.*"
jupyterlab = "4.1.*"
manim = "0.17.*"
matplotlib = "3.8.*"
mpltern = ">=1.0.4,<1.1"
nbconvert = "7.16.*"
numpy = "1.26.*"
openai = ">=1.35.13,<1.36"
pandas = ">=2.2.0,<3"
pip = ">=24.0,<25"
polars = "0.20.*"
pyarrow = "15.0.*"
python = "3.11.*"
quarto = ">=1.4.550,<1.5"
requests = ">=2.32.3,<3"
rich = "12.5.*"
scikit-learn = ">=1.5.0,<1.6"
scipy = "1.13.*"
seaborn = ">=0.13.2,<0.14"
snakemake = {version = "8.11.*", channel = "bioconda"}
spacy = ">=3.7.4,<3.8"
statsmodels = "0.14.*"
sympy = "1.11.*"
typer = ">=0.9.4,<0.10"
libgfortran5 = ">=14"

[environments]
default = { solve-group = "main" }
checks = { features = ["checks"], solve-group = "main" }
build-graphs = { features = ["build-graphs"], no-default-feature = true }

[feature.checks.dependencies]
ruff = "*"
codespell = "*"
pyright = "*"
[feature.checks.tasks]
checks = { depends-on = ["format", "lint", "typecheck", "spellcheck"] }
format = "ruff check --fix --select I; ruff format; exit 0"
lint = "ruff check --extend-select I; exit 0"
spellcheck = "codespell --ignore-words codespell-ignore-words.txt --skip '*.bib,out,playground,gh-pages' && echo 'Spellcheck passed!'; exit 0"
typecheck = "pyright; exit 0"

[feature.build-graphs.dependencies]
snakemake = {version = "8.11.*", channel = "bioconda"}
typer = ">=0.9.4,<0.10"
graphviz = "*"
[feature.build-graphs.tasks]
create-build-graph-dir = "mkdir -p build-graphs"
dag = { cmd = "snakemake --dag | dot -Tsvg > build-graphs/dag.svg", depends-on = ["create-build-graph-dir"] }
rulegraph = { cmd = "snakemake --rulegraph | dot -Tsvg > build-graphs/rulegraph.svg", depends-on = ["create-build-graph-dir"] }
filegraph = { cmd = "snakemake --filegraph | dot -Tsvg > build-graphs/filegraph.svg", depends-on = ["create-build-graph-dir"] }
